name: Update README
'on':
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baoispro/baoispro
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
